<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Satyam" failures="0" tests="1" name="Runners.runner" time="3.530" errors="1" timestamp="15 Oct 2020 13:17:01 GMT" skipped="0">
  <testcase classname="Runners.runner" name="runScenario" time="3.530">
    <error message="Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@2ec99035 , Status Code : 302" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@2ec99035 , Status Code : 302
at apiEngine.endPoints.EndPoints.authenticateUser(EndPoints.java:29)
at stepDefination.defination.i_am_an_authorise_user(defination.java:33)
at âœ½.I am an authorise user(file:///C:/Users/satya.SATYAM/eclipse-workspace/RestAssured/src/test/resources/functions/test.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Runners.runner -->
